export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIES_SUCCESS";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIES_SUCCESS";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIES_SUCCESS";
export const LIKE_MOVIE_SUCCESS = "LIKE_MOVIE_SUCCESS";
export const MOVIE_ACTION_FAIL = "MOVIE_ACTION_FAIL";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";
