export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIES_SUCCESS";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIES_SUCCESS";
// export const SAVE_MOVIE_SUCCESS = "SAVE_MOVIE_SUCCESS";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIES_SUCCESS";
export const LIKE_MOVIE_SUCCESS = "LIKE_MOVIE_SUCCESS";
export const MOVIE_ACTION_FAIL = "MOVIE_ACTION_FAIL";

export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";

export const SET_FILTER_CURRENT_GENRE = "SET_FILTER_CURRENT_GENRE";
export const SET_FILTER_CURRENT_PAGE = "SET_FILTER_CURRENT_PAGE";
export const SET_FILTER_PAGE_SIZE = "SET_FILTER_PAGE_SIZE";
export const SET_FILTER_SEARCH_INPUT = "SET_FILTER_SEARCH_INPUT";
export const SET_FILTER_SORT_COLUMN = "SET_FILTER_SORT_COLUMN";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
