export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const ADD_MOVIES_SUCCESS = "ADD_MOVIES_SUCCESS";
export const UPDATE_MOVIES_SUCCESS = "UPDATE_MOVIES_SUCCESS";
export const DELETE_MOVIES_SUCCESS = "DELETE_MOVIES_SUCCESS";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS";
